---
- hosts: all

  vars_files:
    - params.yml

  gather_facts: no

  tasks:

  - name: Create SSH keypair for root
    user:
      name: root
      generate_ssh_key: yes

  - name: Add list of public SSH keys to authorized_keys file of root
    authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', item) }}"
    with_fileglob:
      - ssh_keys/*.pub

  - name: Allow SSH logins to root via key-based authentication only
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: "^#PermitRootLogin"
      line: "PermitRootLogin without-password"

  - name: Disable tunneled clear text passwords for SSH
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: "^#PasswordAuthentication"
      line: "PasswordAuthentication no"

  - name: Restart the SSH service
    service:
      name: sshd
      state: restarted

  - name: Remove media repository added during installation
    zypper_repository:
      name: "openSUSE-Leap-15.1-1"
      state: absent

  - name: Add repository {{repo_oss_name}}
    zypper_repository:
      name: "{{ repo_oss_name }}"
      repo: "{{ repo_oss_url }}"
      auto_import_keys: yes
      autorefresh: no
      state: present

  - name: Add repository {{repo_oss_upd_name}}
    zypper_repository:
      name: "{{ repo_oss_upd_name }}"
      repo: "{{ repo_oss_upd_url }}"
      auto_import_keys: yes
      autorefresh: yes
      state: present

  - name: Refresh all repositories
    zypper_repository:
      repo: '*'
      runrefresh: yes

  - name: Remove certain packages we do not need anymore
    zypper:
      name: ['qemu-guest-agent', 'btrfsprogs-udev-rules', 'postfix']
      state: absent
 
  - name: Apply any package updates
    zypper:
      name: '*'
      state: latest

  - name: Disable and mask wickedd-dhcp6 service
    systemd:
      name: wickedd-dhcp6
      enabled: no
      masked: yes

  - name: Remove rules from /etc/udev/rules.d/70-persistent-net.rules
    lineinfile:
      path: /etc/udev/rules.d/70-persistent-net.rules
      regexp: '^SUBSYSTEM=="net"'
      state: absent
